Repository Peralban/42sh, pull requests merged in 2023-05, with the labels that each got.

#63 Fix str to word arr
  include/my.h
  lib/my/my_str_to_word_array.c
Labels: bug

#67 Fix str to word arrray again
  .gitignore
  Makefile
  lib/my/my_str_to_word_array.c
  src/my_str_to_array_max_size.c
Labels: bug

#68 66 repository restructuration
  Makefile
  src/builtin/environment/parse_args_setenv.c
  src/builtin/environment/set_environment.c
  src/builtin/environment/setenv.c
  src/builtin/environment/unsetenv.c
  src/ncurse/my_getline_ncurses.c
  src/ncurse/my_put.c
  src/ncurse/my_str_to_array_max_size.c
  src/ncurse/set_get_term_name.c
  src/ncurse/start_ncurses.c
  src/ncurse/write_in_term.c
Labels: enhancement

#69 Fix change directory
  .gitignore
  include/mysh.h
  src/builtin/builtin.c
  src/builtin/environment/set_environment.c
  src/builtin/environment/setenv.c
  src/builtin/my_cd.c
  src/main.c
  src/ncurse/my_str_to_array_max_size.c
  src/ncurse/set_get_term_name.c
  src/prompt/print_prompt.c
Labels: bug

#70 44 history
  .gitignore
  Makefile
  include/mysh.h
  src/history/history.c
  src/main.c
Labels: enhancement

#72 61 advanced parsing to prepare special character
  Makefile
  include/mysh.h
  include/parser.h
  include/special_char.h
  src/builtin/environment/set_get_env.c
  src/builtin/my_exit.c
  src/main.c
  src/ncurse/write_in_term.c
  src/parser/get_token.c
  src/parser/parser.c
Labels: enhancement

#73 add(parser.c): added semicolon
  src/parser/parser.c
Labels: enhancement

#76 50 line edition up and down arrow keys linked to history
  Makefile
  include/mysh.h
  src/history/get_history_array.c
  src/history/history.c
  src/ncurse/get_string.c
  src/ncurse/line_edition/move_in_history.c
  src/ncurse/my_getline_ncurses.c
Labels: enhancement

#77 Fix absolute path
  Makefile
  include/mysh.h
  src/get_file_path.c
  src/history/get_history_array.c
  src/history/history.c
  src/main.c
  src/ncurse/get_string.c
Labels: bug

#78 Delete(get_string): Remove free cause segfault
  src/ncurse/get_string.c
Labels: bug

#81 Fix(pipe_gestion.c): Fix the redirection of the final output to the n…
  src/parser/pipe_gestion.c
Labels: bug

#79 35 separator
  src/builtin/builtin.c
  src/execution/my_exec.c
  src/parser/parser.c
  src/parser/pipe_gestion.c
Labels: enhancement

#80 27 right redirection
  Makefile
  include/mysh.h
  src/redirection/rights_redirections.c
Labels: enhancement

#82 28 double left redirection
  Makefile
  include/mysh.h
  src/redirection/double_left_redirection.c
  src/redirection/rights_redirections.c
Labels: enhancement

#85 Variable handling
  Makefile
  include/mysh.h
  src/builtin/echo.c
  src/main.c
  src/variables/local_variables.c
  src/variables/variables.c
  src/variables/variables_getters.c
  src/variables/variables_special_cases.c
Labels: enhancement

#89 Fix set string
  src/main.c
  src/ncurse/get_string.c
Labels: bug

#92 Fix(get_string): Fix segmentation fault
  src/ncurse/get_string.c
Labels: bug

#94 Rework of setenv
  Makefile
  include/mysh.h
  src/builtin/environment/set_get_env.c
  src/builtin/environment/setenv.c
  src/builtin/environment/setenv_variable.c
  src/execution/my_exec.c
  src/history/history.c
  src/variables/local_variables.c
Labels: bug

#97 Fix project
  Makefile
  include/mysh.h
  src/builtin/environment/set_environment.c
  src/execution/my_exec.c
  src/main.c
  src/ncurse/set_get_term_name.c
  src/prompt/print_prompt.c
Labels: bug

#95 28 double left redirection
  include/mysh.h
  src/ncurse/my_getline_ncurses.c
  src/redirection/double_left_redirection.c
  src/redirection/redirections.c
Labels: enhancement

#99 Fix project
  Makefile
  include/mysh.h
  src/builtin/my_cd.c
  src/execution/check_usr_bin.c
  src/execution/command_error_handling.c
  src/execution/my_exec.c
  src/main.c
Labels: enhancement

#98 Refacto(variables): Change local variable attribution (with set and n…
  Makefile
  include/mysh.h
  src/builtin/builtin.c
  src/builtin/variable_builtins.c
  src/variables/local_variables.c
  src/variables/variables.c
  src/variables/variables_getters.c
Labels: bug

#100 Fix(echo): Move echo execution with the other builtins and add quotes…
  Makefile
  include/mysh.h
  src/builtin/builtin.c
  src/builtin/echo.c
  src/main.c
  src/parser/get_quote.c
  src/parser/get_token.c
  src/parser/parsing_error.c
  src/parser/parsing_error_pipe.c
  src/parser/parsing_error_redir.c
Labels: bug

#101 21 bonus do an option to open sublime txt
  Makefile
  README.md
  include/mysh.h
  src/history/history.c
  src/main.c
  src/ncurse/get_string.c
  src/sublime/cmd_in_sublime.c
Labels: enhancement

#103 71 builtin clear
  Makefile
  include/mysh.h
  src/builtin/builtin.c
  src/builtin/clear_screen.c
Labels: enhancement

#102 40 backticks
  Makefile
  include/mysh.h
  include/parser.h
  include/special_char.h
  src/parser/get_token.c
  src/parser/parser.c
  src/parser/parser_backtick.c
  src/parser/parsing_error.c
  src/parser/parsing_error_pipe.c
  src/parser/parsing_error_redir.c
  src/parser/pipe_gestion.c
Labels: enhancement

#105 Fix(local variables): Patch double variable definition
  src/builtin/variable_builtins.c
Labels: bug

#106 Added(color_gestion.c): Added a fully functionnal color system to the…
  Makefile
  include/my_getline.h
  include/mysh.h
  src/builtin/environment/setenv.c
  src/main.c
  src/ncurse/color_gestion.c
  src/ncurse/my_getline_ncurses.c
  src/ncurse/my_put.c
  src/ncurse/my_str_to_array_max_size.c
  src/ncurse/set_get_term_name.c
  src/ncurse/start_ncurses.c
  src/ncurse/word_array_model.c
  src/ncurse/write_in_term.c
  src/prompt/print_prompt.c
Labels: enhancement

#107 Added(line_editing/cursor_gestion.c): Added a fully functionnal line …
  Makefile
  include/mysh.h
  src/ncurse/get_string.c
  src/ncurse/line_edition/cursor_gestion.c
Labels: enhancement

#109 Add(README): Complete readme
  README.md
Labels: documentation

#110 Refacto(loop): Fix color when ncurses is off
  src/builtin/clear_screen.c
  src/main.c
Labels: bug
